export default function CommentTag(templateState) {
    this.tags = ['nighthawk_header'];

    this.parse = function(parser, nodes, lexer) {
        var tok = parser.nextToken();
        var args = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(tok.value);
        return new nodes.CallExtension(this, 'run', args);
    };

    this.run = function(context, commentChar) {
        if (templateState.hasAddedComment === true) {
            return;
        }
        templateState.hasAddedComment = true;
        return autoGeneratedComment(commentChar);
    };
}

function autoGeneratedComment(commentChar = '//') {
    const generationTime = new Date();
    const headerInfo = `${commentChar} Night Hawk
${commentChar} ------------------------------------------------------------------------------
${commentChar} Authors
${commentChar} -------
${commentChar} Filipe Kiss <hello@filipekiss.com.br> http://github.com/filipekiss
${commentChar} ------------------------------------------------------------------------------
${commentChar} Last changed
${commentChar} ------------
${commentChar} ${generationTime
        .toISOString()
        .substring(0, 16)
        .replace('T', ' ')
        .replace(/\-/g, '/')}
${commentChar} ------------------------------------------------------------------------------`;
    return headerInfo;
}
